### ISSUE TITLE
Admin rights should not be necessary

### ISSUE THREAD

**Issue by uforia** [uforia/MatterBot#21]
The bot currently requires admin rights due to some of the mattermostdriver calls it uses. It's probably possible to make the bot run as a normal user by reworking some code.

**Comment by abushenanigans** [comment]
I can confirm that the bot works as normal user for the matterfeed.py and modules, however requires admin rights for anything related to matterbot.py and commands.

**Comment by uforia** [comment]
> I can confirm that the bot works as normal user for the matterfeed.py and modules, however requires admin rights for anything related to matterbot.py and commands.

Thank you for confirming, that is actually very helpful. I haven't figured out if and how exactly the `mattermostdriver` package defines what commands require admin access. I'm gradually narrowing it down.

**Comment by abushenanigans** [comment]
Any update on this?

**Comment by uforia** [comment]
Not yet; I simply have not had the time to fix this. However, it would really help if you could send me the traceback of the points before this so I know which command(s) are triggering this. We might be able to cooperate and narrow down the Mattermostdriver calls that require admin privileges then and replace them with non-admin versions.

**Comment by TTycho** [comment]
```
ERROR - mattermostdriver.websocket - 2024-02-01 09:07:11,916 - You do not have the appropriate permissions.
ERROR - asyncio - 2024-02-01 09:07:11,927 - Task exception was never retrieved
future: <Task finished name='Task-124' coro=<MattermostManager.handle_message() done, defined at /home/develop/MatterBot/./matterbot.py:70> exception=NotEnoughPermissions('You do not have the appropriate permissions.')>
Traceback (most recent call last):
  File "/home/develop/MatterBot/./matterbot.py", line 75, in handle_message
    await self.handle_post(post_data)
  File "/home/develop/MatterBot/./matterbot.py", line 189, in handle_post
  File "/home/develop/MatterBot/virtualenv/lib/python3.10/site-packages/mattermostdriver/endpoints/channels.py", line 136, in get_channels_for_user
    return self.client.get(
  File "/home/develop/MatterBot/virtualenv/lib/python3.10/site-packages/mattermostdriver/client.py", line 193, in get
    response = self.make_request('get', endpoint, options=options, params=params)
  File "/home/develop/MatterBot/virtualenv/lib/python3.10/site-packages/mattermostdriver/client.py", line 177, in make_request
    raise NotEnoughPermissions(message) from None
mattermostdriver.exceptions.NotEnoughPermissions: You do not have the appropriate permissions.
```

**Comment by TTycho** [comment]
I think you can get rid of the admin rights requirement when you skip the channel checks as matterbot seems to choke on`get_channels_for_user`. This means you need an other way to authorize users for a bot/module.

A clean way to add keep some authorization that is close to the Mattermost model is to use 'teams' instead of channels. 'Teams' are already in the config and the bot checks against them. You could run **matterbot-A** for Team 1 and **matterbot-dev** for those in the dev team.

This allows to run different configs for different teams

Pro's:
- Bots works everywhere, also in newly created channels
- Close to the Mattermost authorization model. Easy to administrate.

Drawbacks:
- Multiple bots to maintain
- Multiple teams in the GUI
- How to handle private messages? Not sure 'Member' status allows to check for the teams the users is in.

@uforia what do you think?

**Comment by uforia** [comment]
Good idea and great find; we'll look into merging it into the existing access controls over time!

**Comment by uforia** [comment]
Currently testing, but seems like Admin rights are no longer needed now.
